#!/bin/bash

#$ -N sub-SUBJECT_fmriprep
#$ -pe smp 10
#$ -q PINC,CCOM,UI
#$ -j y
#$ -o LOGDIR
OMP_NUM_THREADS=8



#Set up dependencies
singularityDir={directory of the singularity files}

# directory of the template files on the server
export TEMPLATEFLOW_HOME={Server directory of the templateflow files}

# directory of the template files in the container
export SINGULARITYENV_TEMPLATEFLOW_HOME=/templateflow

##########

#Run fmriprep
singularity run --cleanenv \
-B /Users/USER/work:/work \
${singularityDir}/fmriprep.sif \
INDIR/ DERIVDIR/ participant --participant-label SUBJECT \
--skip_bids_validation \
--nprocs 8 --omp-nthreads 8 --mem 32000 \
-t rest \
-w work \
--error-on-aroma-warnings -v \
--ignore slicetiming \
--output-spaces MNI152NLin6Asym:res-2 MNI152NLin2009cAsym:res-native \
--bold2t1w-init register \
--bold2t1w-dof 12 --force-bbr \
--slice-time-ref 0.5 \
--dummy-scans 5 \
--use-aroma \
--aroma-melodic-dimensionality -150 \
--fd-spike-threshold 0.5 \
--dvars-spike-threshold 1.5 \
--skull-strip-template OASIS30ANTs \
--skull-strip-fixed-seed \
--skull-strip-t1w force \
--fs-license-file {{Directory of the license file in shared server}} \
--cifti-output 91k \
--output-layout bids \
--resource-monitor \
--notrack \
--stop-on-first-crash

