#!/bin/bash

#$ -N sub-SUBJECT_xcp_d
#$ -pe smp 10
#$ -q PINC,CCOM,UI
#$ -j y
#$ -o LOGDIR
OMP_NUM_THREADS=8



#Set up dependencies
singularityDir=/Shared/boeslab/Software/singularityFiles

scriptDir=/Shared/boeslab/Projects/ECoG_TMS/code
source ${scriptDir}/sourcePack.sh

xcpDir=/Shared/boeslab/Projects/ECoG_TMS/derivatives/xcp_d/sub-SUBJECT/ses-SESSION

##########

#Run XCP-D
singularity run --cleanenv \
-B /Users/USER/work:/work \
${singularityDir}/xcp_d.sif \
PREPDIR XCPDIR participant --participant-label SUBJECT \
--input-type fmriprep \
--smoothing 6 \
-p 36P \
--dummy-scans auto \
--lower-bpf 0.008 \
--upper-bpf 0.08 \
-f 0.5 \
-w work \
--resource-monitor


#HeuDiConv converts data to RPI
#fmriPrep flips data to LPI
#xcp-d keeps data flipped to LPI

#Reorient all xcp-d output to RPI
  #anat
pushd ${xcpDir}/anat > /dev/null
for infile in `ls -1tv *nii.gz`;
  do
  ${scriptDir}/rpiOrient.sh -i ${xcpDir}/anat/${infile}
done
popd > /dev/null

  #func
pushd ${xcpDir}/func > /dev/null
for infile in `ls -1tv *nii.gz`;
  do
  ${scriptDir}/rpiOrient.sh -i ${xcpDir}/func/${infile}
done
popd > /dev/null

